/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2019-05-25 19:13:13 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgresql://username:password@localhost:5432/lose-to-gain -t user_challenge -t challenge -t migrations -t user -s public
 *
 */

export namespace user_challengeFields {
    export type id = number;
    export type challengeId = number;
    export type user1 = number;
    export type user2 = number;

}

export interface user_challenge {
    id: user_challengeFields.id;
    challengeId: user_challengeFields.challengeId;
    user1: user_challengeFields.user1;
    user2: user_challengeFields.user2;

}

export namespace challengeFields {
    export type id = number;
    export type startDate = Date;
    export type data = Object | null;
    export type endDate = Date;

}

export interface challenge {
    id: challengeFields.id;
    startDate: challengeFields.startDate;
    data: challengeFields.data;
    endDate: challengeFields.endDate;

}

export namespace migrationsFields {
    export type id = number;
    export type name = string;
    export type run_on = Date;

}

export interface migrations {
    id: migrationsFields.id;
    name: migrationsFields.name;
    run_on: migrationsFields.run_on;

}

export namespace userFields {
    export type id = number;
    export type email = string | null;
    export type firstName = string | null;
    export type lastName = string | null;
    export type weightLogs = Object | null;
    export type googleId = string | null;

}

export interface user {
    id: userFields.id;
    email: userFields.email;
    firstName: userFields.firstName;
    lastName: userFields.lastName;
    weightLogs: userFields.weightLogs;
    googleId: userFields.googleId;

}
